export default {
    '- INIT -': {
        masterVolume: 0.75,
        gainAttack: 0,
        gainDecay: 0,
        gainSustain: 0.75,
        gainRelease: 0,
        vcoType: 'sine',
        vcoPan: 0,
        delayTime: 0,
        delayFeedback: 0,
        delayTone: 4400,
        delayAmount: 0,
        filterType: 'lowpass',
        filterFreq: 6000,
        filterQ: 0,
        filterAttack: 0,
        filterDecay: 0,
        filterRelease: 0,
        filterEnvAmount: 0,
        reverbType: 'reverb1',
        reverbAmount: 0,
        portamentoSpeed: 0,
        distortionDist: 0,
        distortionAmount: 0,
        vibratoDepth: 0,
        vibratoRate: 0,
        bitCrushDepth: 8,
        bitCrushAmount: 0,
    },
};
